Document: fina
Title: Debian fina Manual
Author: <insert document author here>
Abstract: This manual describes what fina is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/fina/fina.sgml.gz

Format: postscript
Files: /usr/share/doc/fina/fina.ps.gz

Format: text
Files: /usr/share/doc/fina/fina.text.gz

Format: HTML
Index: /usr/share/doc/fina/html/index.html
Files: /usr/share/doc/fina/html/*.html

  
